### ISSUE TITLE
error TS2307: Cannot find module 'node:fs' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ushibutatory** [ushibutatory/umamusume-birthdays#33]
docker build時にエラー。

```
#14 [ 9/10] RUN npm run generate
#14 sha256:76e9bad195206404cf20dfe3a452c834f03cab09d23e758c9278f6d3dfb902a7
#14 0.509 
#14 0.509 > umamusume-birthdays@0.0.1 generate
#14 0.509 > ts-node ts/generator.ts
#14 0.509 
#14 2.878 
#14 2.879 /usr/src/app/node_modules/ts-node/src/index.ts:513
#14 2.879     return new TSError(diagnosticText, diagnosticCodes)
#14 2.879            ^
#14 2.879 TSError: ⨯ Unable to compile TypeScript:
#14 2.879 ts/generator.ts(3,34): error TS2307: Cannot find module 'node:fs' or its corresponding type declarations.
#14 2.879 
#14 2.879     at createTSError (/usr/src/app/node_modules/ts-node/src/index.ts:513:12)
#14 2.879     at reportTSError (/usr/src/app/node_modules/ts-node/src/index.ts:517:19)
#14 2.879     at getOutput (/usr/src/app/node_modules/ts-node/src/index.ts:752:36)
#14 2.879     at Object.compile (/usr/src/app/node_modules/ts-node/src/index.ts:968:32)
#14 2.879     at Module.m._compile (/usr/src/app/node_modules/ts-node/src/index.ts:1056:42)
#14 2.879     at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
#14 2.879     at Object.require.extensions.<computed> [as .ts] (/usr/src/app/node_modules/ts-node/src/index.ts:1059:12)
#14 2.879     at Module.load (node:internal/modules/cjs/loader:972:32)
#14 2.879     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
#14 2.879     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
#14 2.893 npm notice 
#14 2.893 npm notice New minor version of npm available! 7.7.6 -> 7.11.2
#14 2.894 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.11.2>
#14 2.894 npm notice Run `npm install -g npm@7.11.2` to update!
#14 2.894 npm notice 
#14 ERROR: executor failed running [/bin/sh -c npm run generate]: exit code: 1
```

**Comment by ushibutatory** [comment]
ローカルでも `docker build` 時に同様のエラーが発生する。

なお、 `npm run generate` を実行すると、最初は発生しなかったが、npmキャッシュクリアして再インストールしてから実行すると同じエラーが発生するようになった。

パッケージのバージョンを上げたことによって何か変わった？
（05/01に更新した時はエラーは起きなかったが……）

**Comment by ushibutatory** [comment]
ncu -u したうえで実行してもエラーは起こる。

**Comment by ushibutatory** [comment]
importの記述がよくなかったらしい。

- f836dc5bdcc5ea44d71568e0eae675595ea62dc8
